name: build macOS aarch64

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Build release binary
        run: cargo build --release --target=aarch64-apple-darwin
